#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $SPAM_REPO == "MightyXBotSpam" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0JlaW5nTWlnaHR5L01pZ2h0eVhCb3RTcGFtL2FyY2hpdmUvTWlnaHR5LnppcA==" | base64 -d
    elif [[ $SPAM_REPO == "MightyXBotSpam" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0JlaW5nTWlnaHR5L01pZ2h0eVhCb3RTcGFtL2FyY2hpdmUvTWlnaHR5LnppcA==" | base64 -d
    elif [[ $SPAM_REPO =~ $regex ]]
    then
        if [[ $SPAM_REPO_BRANCH ]]
        then
            echo "${SPAM_REPO}/archive/${SPAM_REPO_BRANCH}.zip"
        else
            echo "${SPAM_REPO}/archive/Mighty.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0JlaW5nTWlnaHR5L01pZ2h0eVhCb3RTcGFtL2FyY2hpdmUvTWlnaHR5LnppcA==" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="MightyXBotSpam.zip"
    echo "  Downloading Source Code..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data..."
    HELLPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $HELLPATH
    echo "  • Starting MightyXSpam •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m MightyXSpam
}

start_bot
